### ISSUE TITLE
Do you plan on maintaining this project?

### ISSUE THREAD

**Issue by p-rahul** [LucasBassetti/react-native-chatbot#1]
Thanks for your awesome React Chatbot project! Looks like this repo was created 2 months ago. Was wondering if you plan on porting over the React chatbot project into React Native? Any ETA would be greatly appreciated :-)

**Comment by LucasBassetti** [comment]
Hi,

Thanks for interest in this project! Sorry for the delay do porting it. My mac is reparing and I'm not a experct in React Native. I will try to make it ASAP when I get my mac again.  

Best regards,
Lucas
