### ISSUE TITLE
Enabling text field while selecting an option

### ISSUE THREAD

**Issue by NaveenKumarWL** [LucasBassetti/react-native-chatbot#10]
In this module, we have a feature called selecting options.
In this case text field got disabled. I need a requirement in my app, that needs to allow selecting options and can give text as input through text field.
So can you please support me in this case, that how should I implement this feature in my app.
                                                  Regards,

**Comment by LucasBassetti** [comment]
Hi, sorry for delay.

You can create a next step with a text input for collect the text after a option be selected. 

Example:
```
{
  id: '1',
  options: [
    { value: 1, label: 'Number 1', trigger: '2' },
    { value: 2, label: 'Number 2', trigger: '2' },
  ],
},
{
  id: '2',
  user: true,
  triger: '3',
}
...
```
