### ISSUE TITLE
Dynamic Step Component Example

### ISSUE THREAD

**Issue by kamleshrao** [LucasBassetti/react-native-chatbot#12]
Do you have any example of a Dynamic Step component, which brings data from REST API and injects  them into the react native chat bot?

Thanks!

**Comment by kamleshrao** [comment]
@LucasBassetti Any help in this matter?

**Comment by LucasBassetti** [comment]
Hi, please look here:
[https://lucasbassetti.com.br/react-simple-chatbot/#/docs/wikipedia](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/wikipedia)

**Comment by kamleshrao** [comment]
Thanks @LucasBassetti  - I am building the entire steps JSON in my backend. Is there any way I can bring those steps from REST API and pass it to the  ChatBot component? 

When I try to do so, it is unable to store my JSON into <ChatBot **{steps}**/>

**Comment by kamleshrao** [comment]
@LucasBassetti The Wikipedia Search gets a single data and shows it as result.  I need to bring some steps (options with value/label/trigger data as JSON) from my API. 

Any thoughts on how this can be integrated in Wikipedia example?

**Comment by LucasBassetti** [comment]
If you want loading all steps before start the Chatbot I recommend you do some like that in the render function:

```
loading ? Loading.... : <Chabot steps={steps} />
```

You can't load a specific step if the chat is started but you can create you own custom step. For example: If you want a dynamic option step you can create your own option custom component that will be generated based on previous steps.

**Comment by kamleshrao** [comment]
@LucasBassetti I tried the above in render, but its throwing error.  Note that mine is React Native app.

Code: 
`  render() {
    return (
      <View>
      loading ? <Loading /> : <ChatBot steps={steps} />
      </View>
    );
  }
`

**Error**: 
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

**Comment by LucasBassetti** [comment]
How did you create this `Loading` component?

**Comment by kamleshrao** [comment]
I have just imported it from your package:

`import ChatBot, { Loading } from 'react-simple-chatbot';`

Did I miss anything?

**Comment by LucasBassetti** [comment]
This `Loading` component doesn't exist. You should create your own.

**Comment by kamleshrao** [comment]
I thought it was available. 
Anyways, I did try an alternate, where the "loaded" is always returning "false". It shows me always static steps.  

My logic/pseudocode below: 
```

Constructor:

    this.state = {
      loaded: false,
      dynamicSteps: [],
      staticSteps: [
        {
          id: 'hello-static',
          message: 'Welcome to Static Steps',
          end: true,
        },
      ],
    },


Inside componentWillMount:

    fetch('<rest API endpoint>')
    .then(response => response.json())
    .then(json => {
 
      ... getting data....      
      this.setState({ dynamicSteps: result});
      console.log(this.state.dynamicSteps);
      this.setState( { loaded: true });

    });

In the render: 

 render() { 

   return ( 
    <View> loaded ? <ChatBot steps={dynamicSteps} : <ChatBot steps={staticSteps} /> </View> 
   ); 
 }

```

**Comment by kamleshrao** [comment]
@LucasBassetti any update on this?

**Comment by roshan532** [comment]
please give some ideas how to use the rest API in my chat bot and waiting for your reply
