### ISSUE TITLE
Problem with Android keyboard

### ISSUE THREAD

**Issue by guisn** [LucasBassetti/react-native-chatbot#13]
I don't know where the problem is, but I have already tried many alternative solutions.

Can anybody help me?

![35039053-8430e44c-fb9e-11e7-938d-d4120f8ca334](https://user-images.githubusercontent.com/1149689/35780049-48a9ddf2-09bd-11e8-9e89-876d6d2a4940.png)

**Comment by Taimoormk** [comment]
@guisn I ran into that issue earlier and reported to the owner of this repo. It appears to be a lot of work and may very well take some time to get fixed.

Also, if I may I ask, what have you already tired to fix this issue at your end?

You can check my closed issue [here](https://github.com/LucasBassetti/react-native-chatbot/issues/9)

**Comment by guisn** [comment]
Hi @Taimoormk,

I tried everything the props allowed, but I did not change the package code. That's why I ended up creating this issue with your screenshoot. My next step is to try to modify the package.

**Comment by Taimoormk** [comment]
Hey @guisn thanks for your response.

I haven't got the chance to take a dive into the package yet, but I do feel that the fix is gonna be coming out soon though, hopefully.

**Comment by joaopaulofilho** [comment]
Hi, 

struggling  with this issue, I've found a way to fix this issue on android devices: https://github.com/LucasBassetti/react-native-chatbot/pull/15

**Comment by LucasBassetti** [comment]
I published a new release: `0.0.1-alpha.9`. Please check if it's working now.

**Comment by jeffreymendez1993** [comment]
This added a issue for me. Padding is what works on my device.

**Comment by jeffreymendez1993** [comment]
Maybe the Api Level is what is effecting it.

**Comment by jeffreymendez1993** [comment]
keyboard issue on ios

**Comment by jeffreymendez1993** [comment]
<img width="297" alt="screen shot 2018-02-20 at 10 26 57 pm" src="https://user-images.githubusercontent.com/8095978/36461744-380799bc-168d-11e8-90c5-e5924d99df01.png">

**Comment by Taimoormk** [comment]
@LucasBassetti thanks, I shall have a look this weekend and will let you know.

@guisn thanks man, that helps.

@jeffreymendez1993 I see you are using a Stack Navigation with the chatbot, I know on iOS if you use this chatbot with the Stack Navigation it messes up with the keyboard like you showed. However if you take the Stack Navigation off from the chatbot screen, it works like a charm.

**Comment by Taimoormk** [comment]
@jeffreymendez1993 it may very well be the margin issue, I will have to dive into the repo code and have a look, meanwhile try to take off the stack navigation from this screen and have a look.

**Comment by JacksonMalloy** [comment]
Hey Everyone, 

Android and iOS keyboards are treated differently in Browsers. With the iOS keyboard, Browsers do not subtract viewport height therefore having a height: 100% or a height: 100vh, will not work. With android, the keyboard is actually subtracted from the viewport.  

The image that @guisn posted seems to be from the developers trying to account for the iOS keyboard not affecting the viewport (so they increased the height trying to account for it).

I'm actually curious if anyone has a solution to this problem. Perhaps a method that I am not aware of where you can target the iOS keyboard to check if it is present and then apply custom styling respectively? 

All in all, it's very tedious. Thanks for reading.
