### ISSUE TITLE
iOS keyboard issue.

### ISSUE THREAD

**Issue by jeffreymendez1993** [LucasBassetti/react-native-chatbot#18]
## Description

Add here all the descriptions that you think it will be useful and valuable to this issue.
iOS keyboard issue; ChatComponent is wrapped in a View with flex:1. Content displays fully when keyboard is hidden.
## Screenshots
<img width="295" alt="screen shot 2018-02-20 at 9 29 51 pm" src="https://user-images.githubusercontent.com/8095978/36461781-73a4b9be-168d-11e8-8b3e-9e3d46d8d6ea.png">
<img width="297" alt="screen shot 2018-02-20 at 10 26 57 pm" src="https://user-images.githubusercontent.com/8095978/36461782-73b66574-168d-11e8-9829-99022cad3382.png">

Add screenshots case needes, otherwise delete this section.

**Comment by LucasBassetti** [comment]
Hi,

What version of the Chatbot are you using? If is `0.0.1-alpha.9` try to downgrade to `0.0.1-alpha.8` and tell me if works.

**Comment by jeffreymendez1993** [comment]
@LucasBassetti isn't there a issue on android with the keyboard height in that version ?

**Comment by jeffreymendez1993** [comment]
Im using 0.0.1-alpha.9 also I am on a sim. Testing a device now

**Comment by jeffreymendez1993** [comment]
No luck. I think we have to detect if the text auto fill helper is up and add that to the height to be adjusted.

**Comment by jeffreymendez1993** [comment]
theres a method called relativeKeyboardHeight in keyboard avoiding view that can be used.

**Comment by jeffreymendez1993** [comment]
I removed the View wrapping the content and it works fine but now I cannot place my navigation bar inside the scene.

**Comment by jeffreymendez1993** [comment]
I was able to fix it by setting up the structure like this.
`
      <View>
        <ChatBot
          steps={steps}
          contentStyle={{ paddingTop: 70}}
          botAvatar={base64Logo}/>
        <View style={{position:'absolute', top:0, left:0,right:0}}>
          <NavigationBar title={'Chat Support'} leftBtn={'back'} />
        </View>
      </View>
`

**Comment by jeffreymendez1993** [comment]
<img width="536" alt="screen shot 2018-02-21 at 8 50 44 am" src="https://user-images.githubusercontent.com/8095978/36483513-5a992d22-16e4-11e8-9069-28963bec63c2.png">

**Comment by jeffreymendez1993** [comment]
Actually now it doesn't work for android. @LucasBassetti  can you confirm a scene wrapping ChatBot with a header above it if the keyboard works proper.

**Comment by LucasBassetti** [comment]
Hey @jeffreymendez1993,

What device are you testing?

**Comment by jeffreymendez1993** [comment]
I was on iOS 7. On a Simulator I was able to do a workaround to make it work for both OS systems can close the issue if no one else encountered it.

**Comment by patrykwegrzyn** [comment]
@jeffreymendez1993 Care to share work around ? im expecting this issue when using React navigation

**Comment by Vasant-Patel** [comment]
I am seeing this issue on iOS 11.4 => from iPhone 6s  to  iPhone X

**Comment by DavidTatis** [comment]
Same issue on iOS 12 => from iPhone 7 plus
