### ISSUE TITLE
How to get rid of warning: Failed prop type: the prop 'step' is marked as required in '...', but its value is 'undefined'.

### ISSUE THREAD

**Issue by doublelight** [LucasBassetti/react-native-chatbot#19]
When I'm using a custom component, it always shows tons of warning with all prop, pls show me how to get rid of those.

Failed prop type: the prop 'step' is marked as required in '...', but its value is 'undefined'
Failed prop type: the prop 'steps' is marked as required in '...', but its value is 'undefined'
Failed prop type: the prop 'previousStep' is marked as required in '...', but its value is 'undefined'
Failed prop type: the prop 'TriggerNextStep' is marked as required in '...', but its value is 'undefined'

**Comment by LucasBassetti** [comment]
Can you provide your steps?

**Comment by doublelight** [comment]
as below
![screen shot 2018-03-16 at 8 29 23 am](https://user-images.githubusercontent.com/287563/37499043-59e97e6e-28f4-11e8-83d2-5c987a2b72d8.png)
![screen shot 2018-03-16 at 8 29 53 am](https://user-images.githubusercontent.com/287563/37499044-5a18a36a-28f4-11e8-833f-3193939f474c.png)
![screen shot 2018-03-16 at 8 33 21 am](https://user-images.githubusercontent.com/287563/37499130-bcb5587e-28f4-11e8-8e3f-1f92aadb23ba.png)

**Comment by LucasBassetti** [comment]
Hey @doublelight,

Sorry for big big delay.

Try change `component: (<QuestionChatBotComponent />)` to `component: <QuestionChatBotComponent />` and tell if works

**Comment by doublelight** [comment]
Sadly, it's the same
