### ISSUE TITLE
Build failing?

### ISSUE THREAD

**Issue by footballdaddy** [LucasBassetti/react-native-chatbot#2]
I noticed on travis I see build failing. I did have problems at first install styled-components as a regular dependency. I, furthermore, got warning with prop-types.

**Comment by LucasBassetti** [comment]
Yeah, I will try to fix it. Thanks for reporting!

**Comment by kamleshrao** [comment]
This is still not fixed.  I had to run the below to fix the error.  Please fix this in your code or add this instruction in your README.md 

> yarn add styled-components

After fixing the styled-components error, when I ran the App, I got "**Can't find variable: React**" error. I am going as per the README content

**Comment by kamleshrao** [comment]
I created a new issue with my detailed steps and tasks that i performed to get the Sample Chat Bot working.  Please check the details here: 

https://github.com/LucasBassetti/react-native-chatbot/issues/11
