### ISSUE TITLE
recognitionEnable flag doesn't work

### ISSUE THREAD

**Issue by Shauneoo** [LucasBassetti/react-native-chatbot#25]
## Description

Add here all the descriptions that you think it will be useful and valuable to this issue.

Adding `recognitionEnable={true}` options to chatbot doesnt enable speech recognition. 

`render() {
    return (
        <ChatBot
          recognitionEnable={true}
          steps={steps}
        />
    );
  }`

## Screenshots

Add screenshots case needes, otherwise delete this section.

**Comment by LucasBassetti** [comment]
The recognition is only available in the web version. 

You can find the available props of native [here](https://github.com/LucasBassetti/react-native-chatbot/blob/master/README.md)
