### ISSUE TITLE
Video on react-naive-chabot

### ISSUE THREAD

**Issue by joaojosefilho** [LucasBassetti/react-native-chatbot#39]
Hello! I'm using the 'react-native-chatbot' component, I saw that there is a way to put custom components built into the chat. However, I can only put text and I need to put a video. Can anyone help?

**Comment by Tamsi** [comment]
Hey joaojosefilho, you can do it by using 'react-native-youtube' library

`{
        id: '67',
        component:  <YouTube
                      apiKey=YOUR_APIKEY
                      videoId=YOUR_VIDEOID
                      play={false}
                      controls={1}
                    
                      onReady={e => this.setState({ isReady: true })}
                      onChangeState={e => this.setState({ status: e.state })}
                      onChangeQuality={e => this.setState({ quality: e.quality })}
                      onError={e => this.setState({ error: e.error })}
                    
                      style={styles.videoStyle}
                    />,
      trigger: '68'
      },`

**Comment by joaojosefilho** [comment]
Thank you for your help!
