### ISSUE TITLE
PR For Upgrade but w/ Local storage problems

### ISSUE THREAD

**Issue by juanmndz** [LucasBassetti/react-native-chatbot#4]
I am trying to help convert the Web versions to RN. I have problems though. I can't get the environment setup exactly so I just used "react native init"  and transferred the files over. Maybe using expo will alleviate this environment issue?

https://github.com/juanmndz/rnchatbotclone

Now with the edits I did:
I replace the code by comparing and contrasting the RN and Web version.
It seems to work well but the cache function is something I can't seem to work properly.

I tried for the past days to redit storage.js to work for RN but I figured out the underlying problem is an AsyncStorage storage will not work where it will be called in the componetwillMount from getData)_ in storage.js

Currently when cache is true, it will get the localstorage asynchronously  but will load nothing bc componetwillMount.
https://github.com/juanmndz/rnchatbotclone/blob/master/lib/storage.js

![screenshot from 2017-08-14 10-12-48](https://user-images.githubusercontent.com/16310386/29282839-27836246-80d9-11e7-9fc3-e4d63a56d077.png)

With the data being return :
![screenshot from 2017-08-14 09-57-31](https://user-images.githubusercontent.com/16310386/29282995-bbe41084-80d9-11e7-8b84-6ee4e9dcf7f5.png)

I tried doing with another local storage package but w/o async but I could not ever resolved my promise
https://github.com/juanmndz/rnchatbotclone/blob/master/lib/storagenonasync.js
![screenshot from 2017-08-14 08-18-38](https://user-images.githubusercontent.com/16310386/29283036-e40ebc9e-80d9-11e7-9eb2-77ca989cec24.png)
So it would crash the app.

I really want to get this package up and running, but I have hit a wall atm. I would like to do an official pr if necessary. I just really excited about this package and wish for it to succeed as soon as it can.

**Comment by LucasBassetti** [comment]
Thanks for helping! I think you can ignore the cache the for now.

**Comment by juanmndz** [comment]
I am looking to get an official PR once I have fixes (Honesty it was a simple just copying and pasting and tweak one thing or two) some of the cluttered code (I am a beginner), but I really wanted to implement cache functionality web but Localstorage is synchronous  and storing data is being called in componentwillmount. I will be researching how to alleviate this but atm react-native does not support sync storage.

**Comment by LucasBassetti** [comment]
Hi, maybe you can use [AsyncStorage](https://facebook.github.io/react-native/docs/asyncstorage.html) instead `localStorage`
