### ISSUE TITLE
I catch a error " Module does not exist in the module map"

### ISSUE THREAD

**Issue by wdrich** [LucasBassetti/react-native-chatbot#6]
ChatBotContainer.js`: Module does not exist in the module map
![image](https://user-images.githubusercontent.com/358416/31658763-90c2041a-b2f7-11e7-87db-0e55df8af386.png)

**Comment by mayukh94** [comment]
I'm getting this same error. Any update?

**Comment by ronhsm** [comment]
@mayukh94 how did you solve? im getting the same issue

**Comment by mayukh94** [comment]
@ronhsm  sorry I don't really remember what I had done but I think it was a small mistake on my part. Will let you know if it comes to me.

**Comment by JayricMok** [comment]
same issue , any idea can fix this ?

**Comment by LucasBassetti** [comment]
Please check #9
