### ISSUE TITLE
CustomStep has white background

### ISSUE THREAD

**Issue by chenop** [LucasBassetti/react-native-chatbot#63]
## Description

When using custom component the container has white background with padding

## Screenshots

![image](https://user-images.githubusercontent.com/446575/70037066-9cfcbc80-15be-11ea-82f4-7dfa3d7359e2.png)

need the ability to override CustomStepContainer props.

**Comment by fcataniamm** [comment]
I removed that white box by overriding the **customStyle** prop.
I specified a transparent background and all paddings and margins to 0.

**Comment by chenop** [comment]
@fcataniamm Thanks for responding!
You are right the customStyle prop of the ChatBot component did the job.
