### ISSUE TITLE
Getting error "No component found ARTShape" on including chatbox in JSX 

### ISSUE THREAD

**Issue by linus46** [LucasBassetti/react-native-chatbot#7]
<img width="431" alt="screen shot 2017-11-25 at 9 05 23 am" src="https://user-images.githubusercontent.com/7288104/33226993-d0123568-d1bf-11e7-98ac-c1ec00a89de0.png">

**Comment by tsonev7** [comment]
The link seems to be expired now. Do you mind sharing us how you solved the problem ?

**Comment by otomatik** [comment]
@tsonev7 & @kcedric I solved the problem by following the iOS instruction [here](https://github.com/mohebifar/react-native-loader#ios) (more info on linking for iOS in the [react-native doc](https://facebook.github.io/react-native/docs/linking-libraries-ios.html))
hope this help 😉

**Comment by AnirupPat** [comment]
I am using expo CLI and using the "react-native-chat". Facing the same issue. @otomatik @linus46 please can you help
