### ISSUE TITLE
not able to run app in new version

### ISSUE THREAD

**Issue by musadiq-jinbade** [LucasBassetti/react-native-chatbot#71]
![Screenshot 2020-04-14 at 10 51 49 AM](https://user-images.githubusercontent.com/54430156/79188937-0e3a5f00-7e3e-11ea-9fc4-84cdc7727b1d.png)
## Description

Getting issue while running application 

can we ruse react-native chatbot in react-native version 0.62?

**Comment by musadiq-jinbade** [comment]
remove ART from 'react-native' in node modules
and 
import {Surface, Shape, Path} from '@react-native-community/art';

**Comment by edogbosunny** [comment]
@musadiq-jinbade please what file should this import be? import {Surface, Shape, Path} from '@react-native-community/art';

**Comment by smilydronavalli** [comment]
@musadiq-jinbade  give me the clarification how to solve this issue
then only we are able to use this chatbot npm

Kindly guide me regarding this one and little bit  urgent

Thanks in advance

**Comment by musadiq-jinbade** [comment]
> @musadiq-jinbade give me the clarification how to solve this issue
> then only we are able to use this chatbot npm
> 
> Kindly guide me regarding this one and little bit urgent
> 
> Thanks in advance

I did one thing remove all the npm of a chatbot, style-component.etc

then I just installed this only

npm install --save react-native-chabot styled-components

it will work

**Comment by smilydronavalli** [comment]
I did the it but I got the following error
![Simulator Screen Shot - iPhone 11 - 2020-04-24 at 13 02 57](https://user-images.githubusercontent.com/14346725/80193933-40667080-8637-11ea-8b47-5f5236937b48.png)

kindly guide me

**Comment by smilydronavalli** [comment]
Hi,

This is issue is happened new version of react native.while you intstall 0.61.5 version of react native then this issue is not occured

**Comment by musadiq-jinbade** [comment]
first time I tried and this error was getting for me as well
let me know the react native project version?

**Comment by musadiq-jinbade** [comment]
> Hi,
> 
> This is issue is happened new version of react native.while you intstall 0.61.5 version of react native then this issue is not occured

**Comment by musadiq-jinbade** [comment]
> Hi,
> 
> This is issue is happened new version of react native.while you intstall 0.61.5 version of react native then this issue is not occured

Yes, I tried in new react-native version it was getting error but in 0.61.5 version working fine

**Comment by musadiq-jinbade** [comment]
if you are using new version then you can fix by removing import in node modules and npm community/art...etc

**Comment by musadiq-jinbade** [comment]
> @musadiq-jinbade please what file should this import be? import {Surface, Shape, Path} from '@react-native-community/art';

if you are using new version then you need to import this instead of ART in react native in node modules and npm community/art...etc
