### ISSUE TITLE
Invariant Violation when state.renderedSteps contains a Custom Component

### ISSUE THREAD

**Issue by mediashane** [LucasBassetti/react-native-chatbot#8]
Hey Lucas, awesome project here! I've been stumped for a few days trying to retrieve a conversation from AsyncStorage and set it as the current renderedSteps state, so that old conversations can be loaded.

I've got it all working well, except for conversations that contain a Custom Component, for example a link or image. When trying to load a conversation that has a Custom Component in it, the following error is thrown: 

```
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.

This error is located at:
    in RCTView (at View.js:113)
    in View (created by Styled(View))
    in Styled(View) (at CustomStep.js:45)
    in CustomStep (at ChatBot.js:460)
    in RCTView (at View.js:113)
    in View (at ScrollView.js:748)
    in RCTScrollView (at ScrollView.js:856)
    in ScrollView (at ChatBot.js:545)
    in RCTView (at View.js:113)
    in View (created by Styled(View))
    in Styled(View) (at ChatBot.js:541)
    in ChatBot (at Chat.js:28)
    in Chat (at SceneView.js:31)
```

The Custom Component Container renders and has the Loading dots displaying, but then when it actually tries to load the content of the component the red error screen comes up with the error code pasted above, both in emulators and on actual devices.

I've tried changing how all of the components are exported and imported from files to be as explicit as possible, but the error continues to be thrown. Despite the error message, I don't think it's an export/import issue, because Custom Components are being displayed normally when triggered manually through conversation. 

The Custom Component object data parsed from AsyncStorage looks like this in the logs:

```
Object {
    "component": Object {
      "$$typeof": 60103,
      "_owner": null,
      "_store": Object {},
      "key": null,
      "props": Object {
        "activeOpacity": 0.2,
        "children": Object {
          "$$typeof": 60103,
          "_owner": null,
          "_store": Object {},
          "key": null,
          "props": Object {
            "accessible": true,
            "allowFontScaling": true,
            "children": "Learn more about the Arch of Reunification",
            "ellipsizeMode": "tail",
            "style": Object {
              "color": "#7c9ba5",
            },
          },
          "ref": null,
        },
      },
      "ref": null,
    },
```
Note that when this object is viewed in the logs through normal ChatBot conversation that the "ref"s at the bottom have a little bit more associated data:
```
      "ref": null,
        "type": [Function anonymous],
      },
      "onPress": [Function onPress],
    },
    "ref": null,
    "type": [Function anonymous],
```
Here is the function used to retrieve the renderedSteps from AsyncStorage and set them as current state:
```
async retrievedSteps() {
  try {
    const storedRenderedSteps = await AsyncStorage.getItem('storedRenderedSteps');
    const storedPreviousSteps = await AsyncStorage.getItem('storedPreviousSteps');
    const storedCurrentStep = await AsyncStorage.getItem('storedCurrentStep');
      if (storedRenderedSteps !== null) {
        const parsedRenderedSteps = JSON.parse(storedRenderedSteps);
        const parsedPreviousSteps = JSON.parse(storedPreviousSteps);
        const parsedCurrentStep = JSON.parse(storedCurrentStep);
        this.setState({
          previousStep: parsedPreviousSteps,
          currentStep: parsedCurrentStep,
          renderedSteps: parsedRenderedSteps,
        });
      }
  } catch (error) {
    Alert.alert(error);
  }
}
```
The Custom Component steps are pre-defined locally within the 'steps' array and are not being pulled from a server or remotely. Here is an example:
```
  {
    id: 'Picture 1',
    component: (
      <Image
        style={{ width: 325, height: 233, alignSelf: 'center', borderRadius: 5 }}
        source={require('.././assets/photoOne.png')}
      />
    ),
    triggerNextStep: `Picture 2`,
  },
```

Thanks for any help you're able to give in solving this issue!

**Comment by LucasBassetti** [comment]
Hi @mediashane, thank you!

I used `localStorage` to cache data in the web version. Maybe the code can help you to fix this issue.

You can find the code [here](https://github.com/LucasBassetti/react-simple-chatbot/blob/master/lib/storage.js)

**Comment by mediashane** [comment]
Thanks Lucas! I found my problem in the code you linked, and it was solved by this little if statement:
```
// an error is thrown when render a component from localStorage.
        // So it's necessary reassing the component
        if (renderedStep.component) {
          const id = renderedStep.id;
          data.renderedSteps[i].component = steps[id].component;
        }
```
It appears that components can't be rendered from AsyncStorage in React Native as well! If I can code together a clean solution for ChatBot 'caching' a conversation in RN I will submit a pull request. Cheers!
