### ISSUE TITLE
Module doesn't exist in the module map!

### ISSUE THREAD

**Issue by Taimoormk** [LucasBassetti/react-native-chatbot#9]
As soon as I install and import react-native-chatbot, I am getting following error thrown. It appears to be some missing item in the package, please look into this matter and let me know how to fix this up.

    `// import dependencies here
    import React, { Component } from 'react';
    import { View, StyleSheet } from 'react-native';
    import ChatBot from 'react-native-chatbot';

    // import screens here

    // import components here

    const steps = [
      {
        id: '0',
        message: 'Welcome to react chatbot!',
        trigger: '1',
      },
      {
        id: '1',
        message: 'Bye!',
        end: true,
      },
    ];

    export default class Chat extends Component {
      render() {
        return (
          <View>

          </View>
        );
      }
    }`

![simulator screen shot - iphone 6 - 2017-12-28 at 11 59 37](https://user-images.githubusercontent.com/27800340/34402939-dd021420-ebc6-11e7-8b06-ea8d26238b85.png)

**Comment by LucasBassetti** [comment]
Did you install the `styled-components` package?

**Comment by Taimoormk** [comment]
No. And may I ask how I am supposed to do that? I did check the documentations and couldn't find it anywhere there?

Could you please direct me how to fix this?

**Comment by Taimoormk** [comment]
Don't worry, I found a way to deal with this, thank you.

**Comment by LucasBassetti** [comment]
How did you solve that?

**Comment by Taimoormk** [comment]
I actually installed styled-components by running following command;

`npm install --save styled-components`

the above mentioned issue was fixed, however I ran into solved issue#7 and will go through that fix and will then be hopefully be able to build the chatbot.

**Comment by Taimoormk** [comment]
@LucasBassetti Couple of questions;

a. how am I supposed to retrieve all the user inputs?
b. how am I supposed to email the full chat copy to a couple of recipients from the app?

**Comment by LucasBassetti** [comment]
Hi,

Take a look in the documentation [here](https://lucasbassetti.com.br/react-simple-chatbot/#/docs/chatbot)

You can use the `handleEnd` callback

**Comment by Taimoormk** [comment]
@LucasBassetti Thanks that was very helpful.

Do you know how to fix following overflow view issue as shown in the following screenshot?

![simulator screen shot - iphone 6 - 2018-01-12 at 20 05 33](https://user-images.githubusercontent.com/27800340/34881045-3ae33a92-f7d4-11e7-9064-3f0b6a7dc400.png)

**Comment by LucasBassetti** [comment]
Fixed in `0.0.1-alpha.8`

Thank you!

**Comment by Taimoormk** [comment]
@LucasBassetti thanks for that.

Could you please let me know how to fix keyboard avoiding view as shown in the following screenshot

![simulator screen shot - iphone 6 - 2018-01-16 at 16 46 52](https://user-images.githubusercontent.com/27800340/34987473-156e9b92-fadd-11e7-80c4-a5d90da3b337.png)

**Comment by Taimoormk** [comment]
And on Android we are having such keyboard view...

![screenshot_1516186232](https://user-images.githubusercontent.com/27800340/35039053-8430e44c-fb9e-11e7-938d-d4120f8ca334.png)

**Comment by LucasBassetti** [comment]
Hi @Taimoormk,

This look a more complex issue. I will need some time to fix it.

Thank you for reporting!

**Comment by Taimoormk** [comment]
@LucasBassetti cheers! I shall look forward to see its fix in the due course, thanks for letting me know.

**Comment by LucasBassetti** [comment]
Hey @Taimoormk,

What phone and android version are you using?

**Comment by Taimoormk** [comment]
Hey @LucasBassetti I am only using the Android Emulator, using Pixel XL API 23.

**Comment by Taimoormk** [comment]
@LucasBassetti any luck so far?

**Comment by LucasBassetti** [comment]
Hi @Taimoormk,

Sorry I didn't have time to look this properly. But I think can be related with this:
[https://facebook.github.io/react-native/docs/keyboardavoidingview.html#behavior](https://facebook.github.io/react-native/docs/keyboardavoidingview.html#behavior)

**Comment by joaopaulofilho** [comment]
Hi @LucasBassetti 
I made this behavior platform aware and submitted a PR, so this could work ok on android devices: https://github.com/LucasBassetti/react-native-chatbot/pull/15

**Comment by Taimoormk** [comment]
@joaopaulofilho thanks man, much appreciate it.
